# Generated by Django 3.0 on 2020-01-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_auto_20200119_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pdf',
            new_name='file',
        ),
    ]
